# Generated by Django 4.1.7 on 2023-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentid',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
